export const GET_WEATHER_ZIPCODE_REQUEST = "GET_WEATHER_ZIPCODE_REQUEST";
export const GET_WEATHER_ZIPCODE_SUCCESS = "GET_WEATHER_ZIPCODE_SUCCESS";
export const GET_WEATHER_ZIPCODE_FAIL = "GET_WEATHER_ZIPCODE_FAIL";